// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIfPBOPuj5zqvcSOonY8SDDLjxe0pLFfs',
    appId: '1:653629473547:web:d7ecfd91afe9aa26d8980e',
    messagingSenderId: '653629473547',
    projectId: 'chart-a7076',
    authDomain: 'chart-a7076.firebaseapp.com',
    databaseURL: 'https://chart-a7076-default-rtdb.firebaseio.com',
    storageBucket: 'chart-a7076.appspot.com',
    measurementId: 'G-73NKX6ZWSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzJlAbLYRz1S4RddTZj4eGTdzAEa4KyNo',
    appId: '1:653629473547:android:1b065f3eaf1fac84d8980e',
    messagingSenderId: '653629473547',
    projectId: 'chart-a7076',
    databaseURL: 'https://chart-a7076-default-rtdb.firebaseio.com',
    storageBucket: 'chart-a7076.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByGSw6t5LflDM63HwUeIMVaathRtI7-VY',
    appId: '1:653629473547:ios:4ceb322b3f3b715dd8980e',
    messagingSenderId: '653629473547',
    projectId: 'chart-a7076',
    databaseURL: 'https://chart-a7076-default-rtdb.firebaseio.com',
    storageBucket: 'chart-a7076.appspot.com',
    iosBundleId: 'com.example.chart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByGSw6t5LflDM63HwUeIMVaathRtI7-VY',
    appId: '1:653629473547:ios:4ceb322b3f3b715dd8980e',
    messagingSenderId: '653629473547',
    projectId: 'chart-a7076',
    databaseURL: 'https://chart-a7076-default-rtdb.firebaseio.com',
    storageBucket: 'chart-a7076.appspot.com',
    iosBundleId: 'com.example.chart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIfPBOPuj5zqvcSOonY8SDDLjxe0pLFfs',
    appId: '1:653629473547:web:783ab5d8980f324bd8980e',
    messagingSenderId: '653629473547',
    projectId: 'chart-a7076',
    authDomain: 'chart-a7076.firebaseapp.com',
    databaseURL: 'https://chart-a7076-default-rtdb.firebaseio.com',
    storageBucket: 'chart-a7076.appspot.com',
    measurementId: 'G-9F3YP1TF26',
  );
}
